build.gradle
src/main/java/gov/cms/ab2d/fetcher/EOBFetcher.java
src/main/java/gov/cms/ab2d/fetcher/FetcherHandler.java

Now running Spring within a lambda and am able to make a BFDClient call to fetch EOBs.

Incorporated BFD Client into a Lambda

---

src/main/resources/logback.xml

Added a log configuration file so that we only see INFO or higher log messages.

AB2D-4775: Suppress debug loggging

---

build.gradle
src/main/java/gov/cms/ab2d/fetcher/model/EOBFetchParams.java
src/main/java/gov/cms/ab2d/fetcher/model/JobFetchPayload.java
src/main/java/gov/cms/ab2d/fetcher/model/PatientCoverage.java
src/main/java/gov/cms/ab2d/worker/processor/PatientClaimsCollector.java
src/main/java/gov/cms/ab2d/worker/processor/PatientClaimsProcessorImpl.java
src/main/java/gov/cms/ab2d/worker/processor/ProgressTrackerUpdate.java

Incorporated the current worker code into the lambda.
Still need to actually hook it up and test it.  This PR is just to give folks an early look.

AB2D-4776: Fetch, Filter and Persist EOBs

---

Jenkinsfile
build.gradle
eob-fetcher/build.gradle
eob-fetcher/src/main/java/gov/cms/ab2d/worker/processor/MockEventClient.java
eob-fetcher/src/main/java/gov/cms/ab2d/worker/processor/PatientClaimsProcessorImpl.java
metrics-lambda/build.gradle

**JIRA Tickets:**
[AB2D-5223](https://jira.cms.gov/browse/AB2D-5223) - Create SBOM for AB2D for ION Channel
Adds the ability to create an SBOM for the code base and then has it triggered by Jenkins during the build and test process.
To actually access the SBOM, look at the latest build in Jenkins, go to the workspace where the build occurs and the SBOM exists as both JSON and XML in the build/reporting directory

Add support for SBOM

---

.github/pull_request_template.md

**JIRA Tickets:**
[AB2D-5519](https://jira.cms.gov/browse/AB2D-5519) - PR Templates - Security Section
Adds standard security section to pull request template.

  AB2D-5519: PR Templates - Security Section

---

eob-fetcher/build.gradle
lambda-test-utils/build.gradle

https://jira.cms.gov/browse/AB2D-5482
Bump:
[mockito](https://github.com/CMSgov/ab2d-lambdas/pull/39)
[newrelic](https://github.com/CMSgov/ab2d-lambdas/pull/42)
[jackson](https://github.com/CMSgov/ab2d-lambdas/pull/44)
[hapi-fhir-structures-dstu](https://github.com/CMSgov/ab2d-lambdas/pull/45)
This PR addresses dependabot PR's for Sprint 4

AB2D-5482 Sprint 4: Perform Dependabot Updates by the end of each sprint

---

database-management/src/main/resources/db/changelog/2023/create-ab2d-analyst.sql
database-management/src/main/resources/db/changelog/changelog.yaml

https://jira.cms.gov/browse/AB2D-5482
https://github.com/CMSgov/ab2d-lambdas/pull/46
Liquibase migration for adding a new role when its missing
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
Please make sure the pipelines passes without error:
(https://jenkins.ab2d.cms.gov/job/AB2D%20Lambdas/job/ab2d-lambdas/job/main/)

added liquibase migration for ab2d-Analyst role

---

database-management/src/main/resources/db/changelog/2023/create-ab2d-analyst.sql
database-management/src/main/resources/db/changelog/changelog.yaml
optout/src/main/java/gov/cms/ab2d/optout/OptOutConsumer.java
optout/src/main/java/gov/cms/ab2d/optout/OptOutProducer.java

https://jira.cms.gov/browse/AB2D-5564
Created new AWS Lambda to stream local dummy file for opt-out feature
AWS Lambda includes logic:
Stream a dummy file from resources (will be changed in the [AB2D-5568](https://jira.cms.gov/browse/AB2D-5568))
Parse the file line by line and retrieve mbi, effective date and optout flag
Print results in logs
The CCLF BCDA file was taken as an example for a dummy file.
Added unit tests and tested manually on local environment
INFO --- [uncthread150] l.s.a.lambda_executors     : Successfully executed lambda "arn:aws:lambda:us-east-1:000000000000:function:OptOutHandler"

AB2D 5564/create optout lambda

---

optout/src/test/java/gov/cms/ab2d/optout/OptOutProcessingTest.java
optout/src/test/resources/optOutDummy.txt

https://jira.cms.gov/browse/AB2D-6008
Replaced test data for OptOut Lambda  
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
Unit tests passed

AB2D-6008 Replace test data

---

attribution-data-file-share/src/test/java/gov/cms/ab2d/attributionDataShare/AttributionDataShareTest.java
optout/src/main/java/gov/cms/ab2d/optout/OptOutHandler.java
optout/src/main/java/gov/cms/ab2d/optout/OptOutProcessor.java
optout/src/test/java/gov/cms/ab2d/optout/OptOutHandlerTest.java
optout/src/test/java/gov/cms/ab2d/optout/OptOutProcessorTest.java

https://jira.cms.gov/browse/AB2D-6008
Renamed a couple of files in ab2d-lambdas
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
(How were the changes verified? Did you fully test the acceptance criteria in the ticket? Provide reproducible testing instructions and screenshots if applicable.)

AB2D-6008 Incident cleanup

---

attribution-data-file-share/src/main/java/gov/cms/ab2d/attributionDataShare/AttributionDataShareHelper.java

https://jira.cms.gov/browse/AB2D-6039
(What was added, updated, or removed in this PR.)
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
(How were the changes verified? Did you fully test the acceptance criteria in the ticket? Provide reproducible testing instructions and screenshots if applicable.)

Ab2D-6039/Troubleshooting prod

---

attribution-data-file-share/src/main/java/gov/cms/ab2d/attributionDataShare/AttributionDataShareHelper.java
optout/src/main/java/gov/cms/ab2d/optout/OptOutProcessor.java

https://jira.cms.gov/browse/AB2D-xxx
Added printing out last line to logs
Tested on Impl:
2024-04-24T13:22:33.290-07:00 | File trailer: TRL_BENECONFIRM202404240000000007

Add printing out trailer line to logs

---

Jenkinsfile

https://jira.cms.gov/browse/PLT-749
Need a newer version of jdk

Update java version in jenkinsfile

---

.github/workflows/publish-lambdas.yml

https://jira.cms.gov/browse/PLT-919
Swap Publish lambdas from jenkins to GHA
Testing validated

PLT-919 switch publish lambdas to GHA

---

metrics-lambda/src/main/java/gov/cms/ab2d/metrics/CloudwatchEventHandler.java
metrics-lambda/src/test/java/gov/cms/ab2d/metrics/CloudwatchEventHandlerTest.java

https://jira.cms.gov/browse/AB2D-6727
Fix queue name in `CloudwatchEventHandler`
Queue name should match greenfield SQS queue
N/A

Fix queue name in CloudwatchEventHandler

---

optout/src/test/java/gov/cms/ab2d/optout/OptOutProcessorTest.java

https://jira.cms.gov/browse/AB2D-6716
Fix for unit tests
There are some failures for the optout lambda
https://github.com/CMSgov/ab2d-lambdas/actions/runs/15573334580/job/43853577199

AB2D-6716/fix tests

---

metrics-lambda/src/main/java/gov/cms/ab2d/metrics/CloudwatchEventHandler.java
metrics-lambda/src/test/java/gov/cms/ab2d/metrics/CloudwatchEventHandlerTest.java
retrieve-hpms-counts/src/main/java/gov/cms/ab2d/retrievehpmscounts/HPMSCountsHandler.java

https://jira.cms.gov/browse/AB2D-6727
Terraform changed SQS queue name from e.g. `ab2d-test-events-sqs` to `ab2d-test-events` and this code must be updated.

Fix SQS name -- remove '-sqs' suffix

---

.github/workflows/opt-out-export-deploy-gf.yml
.github/workflows/opt-out-export-dev-deploy.yml
.github/workflows/opt-out-export-test-deploy.yml
.github/workflows/opt-out-export-unit.yml
.github/workflows/opt-out-import-deploy-gf.yml
.github/workflows/opt-out-import-dev-deploy.yml
.github/workflows/opt-out-import-test-deploy.yml
.github/workflows/opt-out-import-unit.yml
.github/workflows/publish-lambdas-gf.yml
.github/workflows/publish-lambdas.yml

https://jira.cms.gov/browse/PLT-657
references to ab2d-bcda-dpc-platform renamed to cdap
we are renaming the ab2d-bcda-dpc-platform repo to cdap
upon approval, ab2d-bcda-dpc-platform repo will be renamed to cdap and workflow re-ran, if successful PR merged if not ab2d-bcda-dpc-platform repo rename to cdap reverted while investigating why workflow failed

PLT-657:Rename the public platform github repo

---

attribution-data-file-share/src/main/java/gov/cms/ab2d/attributiondatashare/AttributionDataShareConstants.java
build.gradle
optout/src/main/java/gov/cms/ab2d/optout/OptOutConstants.java

- https://jira.cms.gov/browse/AB2D-6743
- https://jira.cms.gov/browse/AB2D-6758
- Remove references to `public` schema
**This PR depends on the DB migration script from this PR**
- https://github.com/CMSgov/ab2d/pull/1525
Validated in test environment

Remove references to public schema

---

README.md

https://jira.cms.gov/browse/AB2D-6791
Update the README to point future selves to the updated lambdas directory homed in the [primary ab2d project](https://github.com/CMSgov/ab2d).
Post greenfield migration.
n/a

AB2D-6791: Prepare repository for archival
